#! /usr/bin/env Rscript
library('knitr')
library('crayon')
library('formatR')

fname = "slides"
tex_fname = paste(fname,".tex",sep="")
aux_fname = paste(fname,".aux",sep="")
log_fname = paste(fname,".log",sep="")
rnw_fname = paste(fname,".Rnw",sep="")

oldmt = file.info(dir(recursive=TRUE))[,"mtime",drop=FALSE]

while(TRUE){

    old_files = rownames(oldmt)
    old_files = old_files[grepl(".tex$",old_files)]

    mt = file.info(dir(recursive=TRUE))[,"mtime",drop=FALSE]
    updt = any(mt[old_files,,drop=FALSE] > oldmt[old_files,,drop=FALSE])

    if(updt){
        cat(blue("Running LaTex.\n"))
        toss = system(paste("rm",aux_fname),intern=TRUE)
        toss = system(paste("pdflatex -interaction=batchmode",tex_fname),intern=TRUE)
        toss = system(paste("pdflatex -interaction=batchmode",tex_fname),intern=TRUE)
        out = system(paste("grep \"!\"",log_fname))        
        if(out == 1){
            cat(green("OK\n"))
        } else {
            cat(red("ERROR\n"))
        }
        cat("==========")
    }
    oldmt = mt
    Sys.sleep(1/10)
}
